<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ABP_TestAssignment.Infrastructure\ABP_TestAssignment.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="AutoMapper" Version="16.2.0" />
	<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
	<PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.11" />
	<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
	<PackageReference Include="NSec.Cryptography" Version="25.4.0" />
	<PackageReference Include="Quartz" Version="3.17.1" />
	<PackageReference Include="Quartz.Extensions.Hosting" Version="3.17.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AutoMapper\" />
    <Folder Include="BusinessServices\" />
  </ItemGroup>

</Project>
