// <auto-generated />
using System;
using ABP_TestAssignment.Infrastructure.EFRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ABP_TestAssignment.Infrastructure.PostgresMigrations
{
    [DbContext(typeof(EFDataContext))]
    [Migration("20260829111711_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ABP_TestAssignment.Domain.Entities.Bookings.Booking", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BookingEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BookingStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CalculatedTotalPrice")
                        .HasColumnType("numeric(12,2)");

                    b.Property<long>("CompanyID")
                        .HasColumnType("bigint");

                    b.Property<long>("RoomID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("BookingStartTime");

                    b.HasIndex("CompanyID");

                    b.HasIndex("RoomID");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("ABP_TestAssignment.Domain.Entities.Companies.Company", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<short>("Role")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Company");
                });

            modelBuilder.Entity("ABP_TestAssignment.Domain.Entities.Rooms.Room", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<decimal>("BasePricePerHour")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Room");
                });

            modelBuilder.Entity("ABP_TestAssignment.Domain.Entities.Services.Service", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Service");
                });

            modelBuilder.Entity("ABP_TestAssignment.Domain.Entities.Tokens.InvalidatedToken", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenID")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("ID");

                    b.HasIndex("TokenID");

                    b.ToTable("InvalidatedToken");
                });

            modelBuilder.Entity("BookingService", b =>
                {
                    b.Property<long>("BookingID")
                        .HasColumnType("bigint");

                    b.Property<long>("ServicesID")
                        .HasColumnType("bigint");

                    b.HasKey("BookingID", "ServicesID");

                    b.HasIndex("ServicesID");

                    b.ToTable("BookingService");
                });

            modelBuilder.Entity("RoomService", b =>
                {
                    b.Property<long>("AvailableServicesID")
                        .HasColumnType("bigint");

                    b.Property<long>("RoomID")
                        .HasColumnType("bigint");

                    b.HasKey("AvailableServicesID", "RoomID");

                    b.HasIndex("RoomID");

                    b.ToTable("RoomService");
                });

            modelBuilder.Entity("ABP_TestAssignment.Domain.Entities.Bookings.Booking", b =>
                {
                    b.HasOne("ABP_TestAssignment.Domain.Entities.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ABP_TestAssignment.Domain.Entities.Rooms.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BookingService", b =>
                {
                    b.HasOne("ABP_TestAssignment.Domain.Entities.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ABP_TestAssignment.Domain.Entities.Services.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoomService", b =>
                {
                    b.HasOne("ABP_TestAssignment.Domain.Entities.Services.Service", null)
                        .WithMany()
                        .HasForeignKey("AvailableServicesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ABP_TestAssignment.Domain.Entities.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ABP_TestAssignment.Domain.Entities.Rooms.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
